// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9_klT0xK7jQTGlTt4BntrFdM6PPW44yI',
    appId: '1:228493690274:web:fb7bfceb300881eb3b9efb',
    messagingSenderId: '228493690274',
    projectId: 'noraf-ba452',
    authDomain: 'noraf-ba452.firebaseapp.com',
    storageBucket: 'noraf-ba452.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtAczFD6wwxZ-sYWA3O7HSv_kBkByC1sY',
    appId: '1:228493690274:android:b67c2a5389e874503b9efb',
    messagingSenderId: '228493690274',
    projectId: 'noraf-ba452',
    storageBucket: 'noraf-ba452.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc-AnQAD8Xnfh72X6Jk4OkmpI5rSN7Kn0',
    appId: '1:228493690274:ios:7644807a3996e3f43b9efb',
    messagingSenderId: '228493690274',
    projectId: 'noraf-ba452',
    storageBucket: 'noraf-ba452.appspot.com',
    iosClientId: '228493690274-ee854lbl6ui5iutsda9saijgojdaeu35.apps.googleusercontent.com',
    iosBundleId: 'com.fodioaharh.noraf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc-AnQAD8Xnfh72X6Jk4OkmpI5rSN7Kn0',
    appId: '1:228493690274:ios:e37c97de7f118e073b9efb',
    messagingSenderId: '228493690274',
    projectId: 'noraf-ba452',
    storageBucket: 'noraf-ba452.appspot.com',
    iosClientId: '228493690274-qrh2m8cn566reomsrpdvk6vquo5d7pmj.apps.googleusercontent.com',
    iosBundleId: 'com.fodioaharh.noraf.RunnerTests',
  );
}
